name: HW‑in‑the‑Loop

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hitl:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Allure CLI
        run: |
          choco install allure --yes
      - name: Run deploy & tests
        shell: pwsh
        run: ./scripts/deploy_and_test.ps1
      - name: Auto‑commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "results/${{ github.sha }}"
          push_options: '--force'
